obstacle_range: 3.0
raytrace_range: 3.5
#footprint: [[-0.110, -0.133], [-0.110, 0.133],[0.110, 0.133], [0.110, -0.133]]
#robot_radius: ir_of_robot
footprint: [[-0.205, -0.155], [-0.205, 0.155], [0.077, 0.155], [0.077, -0.155]]
#robot_radius: 0.25 # distance a circular robot should be clear of the obstacle

inflation_radius: 2.0
cost_scaling_factor: 3.0

map_type: costmap
observation_sources: laser_scan_sensor
scan: {sensor_frame: hokuyo, data_type: LaserScan, topic: /devastator/laser/scan, marking: true, clearing: true}

#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}
